name: Test Torsdag deployment skiss

on:
  schedule:
    - cron: "0 20 * * 4"
  workflow_dispatch:
      inputs:
        branch-api:
          description: "Branch zoplanner-api"
          required: true
          default: "dev"
        branch-service:
          description: "Branch zoplanner-service"
          required: true
          default: "dev"
        branch-notificationservice:
          description: "Branch zoplanner-notificationservice"
          required: true
          default: "dev"

jobs:
  zoplanner-api:
    name: Test & build ZoPlanner API
    runs-on: ubuntu-latest
    steps:
      - name: Invoke zoplanner-api workflow
        uses: the-actions-org/workflow-dispatch@v4
        with:
          workflow: 205960695
          repo: zocom-utveckling/zoplanner-api
          ref: ${{ github.event.inputs.branch-api || 'dev' }}
          wait-for-completion: true
          token: '${{secrets.TOKEN}}'

  zoplanner-service:
    name: Test & build ZoPlanner Service
    needs: zoplanner-api
    runs-on: ubuntu-latest
    steps:
      - name: Invoke zoplanner-service workflow
        uses: the-actions-org/workflow-dispatch@v4
        with:
          workflow: 251174415
          repo: zocom-utveckling/zoplanner-service
          ref: ${{ github.event.inputs.branch-service || 'dev' }}
          wait-for-completion: true
          token: '${{secrets.TOKEN}}'
  
  zoplanner-notificationservice:
    name: Test & build ZoPlanner Notificationservice
    needs: [zoplanner-api, zoplanner-service]
    runs-on: ubuntu-latest
    steps:
      - name: Invoke zoplanner-notificationservice workflow
        uses: the-actions-org/workflow-dispatch@v4
        with:
          workflow: 251174415
          repo: zocom-utveckling/zoplanner-service
          ref: ${{ github.event.inputs.branch-service || 'dev' }}
          wait-for-completion: true
          token: '${{secrets.TOKEN}}'
  deploy:
    name: Deploy
    needs: [zoplanner-api, zoplanner-service, zoplanner-notificationservice]
    runs-on: ubuntu-latest
    steps:
      - run: echo "All tests passed"
