name: ZoPlanner CI/CD

on:
  schedule:
    - cron: "0 20 * * 4"
  workflow_dispatch:

jobs:
  zoplanner-api:
    name: Build & test ZoPlanner API
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_USER: "${{secrets.POSTGRES_USER}}"
          POSTGRES_PASSWORD: "${{secrets.POSTGRES_PASSWORD}}"
          POSTGRES_DB: zoplanner
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      HOST: localhost
      PORT: 5432
      POSTGRES_USER: "${{secrets.POSTGRES_USER}}"
      POSTGRES_PASSWORD: "${{secrets.POSTGRES_PASSWORD}}"
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: zocom-utveckling/zoplanner-api
          ref: 'main'
          path: zoplanner-api
          token: "${{secrets.TOKEN}}"

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          
      - name: Maven build and test
        run: mvn clean verify
        working-directory: ./zoplanner-api/webapi

      

  zoplanner-notificationservice:
    name: Build & test ZoPlanner Notificationservice
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: zocom-utveckling/zoplanner-notificationservice
          ref: 'main' 
          path: zoplanner-notificationservice
          token: "${{secrets.TOKEN}}"


      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Maven build and run tests
        run: mvn -B clean verify
        working-directory: ./zoplanner-notificationservice

  zoplanner-service:
    name: Build & test ZoPlanner Service
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: zocom-utveckling/zoplanner-service
          ref: 'main'
          path: zoplanner-service
          token: "${{secrets.TOKEN}}"

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'

      - name: ls
        run: ls -R
        
      - name: Restore dependencies
        run: dotnet restore zoplanner-service.sln
        working-directory: zoplanner-service


      - name: Build
        run: dotnet build zoplanner-service.sln --no-restore --configuration Release
        working-directory: zoplanner-service


      - name: Run tests
        run: dotnet test zoplanner-service.sln --no-build --configuration Release --verbosity normal
        working-directory: zoplanner-service


  zoplanner-frontend:
    name: Build & test Vite React
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: zocom-utveckling/zoplanner-frontend
          ref: main
          token: ${{secrets.TOKEN}}
          path: zoplanner-frontend
      - run: echo "There are no tests right now :("
        
  deploy:
    name: Deploy
    needs: [zoplanner-api, zoplanner-service, zoplanner-notificationservice, zoplanner-frontend]
    runs-on: zocom-ubuntu
    steps:

      - name: Checkout zoplanner-api
        uses: actions/checkout@v4
        with:
          repository: zocom-utveckling/zoplanner-api
          ref: main
          path: zoplanner-api
          token: ${{secrets.TOKEN}}
          
      - name: Checkout zoplanner-service
        uses: actions/checkout@v4
        with:
          repository: zocom-utveckling/zoplanner-service
          ref: main
          path: zoplanner-service
          token: ${{secrets.TOKEN}}

      - name: Checkout zoplanner-notificationservice
        uses: actions/checkout@v4
        with:
          repository: zocom-utveckling/zoplanner-notificationservice
          ref: main
          path: zoplanner-notificationservice
          token: ${{secrets.TOKEN}}

      - name: Checkout zoplanner-frontend
        uses: actions/checkout@v4
        with:
          repository: zocom-utveckling/zoplanner-frontend
          ref: main
          path: zoplanner-frontend
          token: ${{secrets.TOKEN}}

    # Postgres backup and restore?
    # Starta ZoPlanner med docker
